/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    '[data-theme=light]',
    '[data-theme=dark]',
    '[data-theme=cupcake]',
    '[data-theme=bumblebee]',
    '[data-theme=emerald]',
    '[data-theme=corporate]',
    '[data-theme=synthwave]',
    '[data-theme=retro]',
    '[data-theme=cyberpunk]',
    '[data-theme=valentine]',
    '[data-theme=halloween]',
    '[data-theme=garden]',
    '[data-theme=forest]',
    '[data-theme=aqua]',
    '[data-theme=lofi]',
    '[data-theme=pastel]',
    '[data-theme=fantasy]',
    '[data-theme=wireframe]',
    '[data-theme=black]',
    '[data-theme=luxury]',
    '[data-theme=dracula]',
    '[data-theme=cmyk]',
    '[data-theme=autumn]',
    '[data-theme=business]',
    '[data-theme=acid]',
    '[data-theme=lemonade]',
    '[data-theme=night]',
    '[data-theme=coffee]',
    '[data-theme=winter]',
    '[data-theme=dim]',
    '[data-theme=nord]',
    '[data-theme=sunset]',
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      'light', 'dark', 'cupcake', 'bumblebee', 'emerald', 'corporate',
      'synthwave', 'retro', 'cyberpunk', 'valentine', 'halloween', 'garden',
      'forest', 'aqua', 'lofi', 'pastel', 'fantasy', 'wireframe', 'black',
      'luxury', 'dracula', 'cmyk', 'autumn', 'business', 'acid', 'lemonade',
      'night', 'coffee', 'winter', 'dim', 'nord', 'sunset',
    ],
    darkTheme: false,  // 禁用自動深色模式檢測
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
}
